[
  { "question": "What is your name?", "answer": "I'm the MongoBot, powered by NestJS!" },
  { "question": "How are you?", "answer": "I'm a collection of documents, so I'm feeling quite organized!" },
  { "question": "What is NestJS?", "answer": "NestJS is a progressive Node.js framework for building efficient server-side applications." },
  { "question": "What is MongoDB?", "answer": "MongoDB is a NoSQL database that stores data in flexible, JSON-like documents." },
  { "question": "Where is your office?", "answer": "We are a fully remote team operating from the cloud." },
  { "question": "How do I contact support?", "answer": "You can email us at support@example.com." },
  { "question": "What are your opening hours?", "answer": "We are open 24/7, just like this database." },
  { "question": "Who created you?", "answer": "I was created by a developer learning the MERN stack!" },
  { "question": "Do you like SQL?", "answer": "I prefer the flexibility of NoSQL, but I respect my relational cousins." },
  { "question": "Tell me a joke.", "answer": "Why did the developer go broke? Because he used up all his cache!" },
  { "question": "What is the capital of France?", "answer": "That's Paris, though I'm better at database queries than geography." },
  { "question": "How do I reset my password?", "answer": "Click the 'Forgot Password' link on the login screen." },
  { "question": "Is my data secure?", "answer": "Yes, we use industry-standard encryption for all stored data." },
  { "question": "What is an API?", "answer": "An API is a set of rules that allows different software entities to communicate." },
  { "question": "Do you support TypeScript?", "answer": "Absolutely! NestJS is built with and for TypeScript." },
  { "question": "What is Mongoose?", "answer": "Mongoose is an ODM that provides a straight-forward, schema-based solution to model your application data." },
  { "question": "Can I use Docker?", "answer": "Yes, Docker is highly recommended for running MongoDB locally." },
  { "question": "How do I update my profile?", "answer": "Go to Settings > Profile to edit your information." },
  { "question": "What is a document in Mongo?", "answer": "A document is a record in a MongoDB collection and the basic unit of data." },
  { "question": "What is a collection?", "answer": "A collection is a group of MongoDB documents, similar to a table in RDBMS." },
  { "question": "How do I delete my account?", "answer": "Please contact our admin team to process account deletions." },
  { "question": "What version of Node should I use?", "answer": "We recommend the latest LTS version (currently v20 or v22)." },
  { "question": "Do you have a mobile app?", "answer": "Not yet, but our web interface is fully responsive!" },
  { "question": "How do I contribute?", "answer": "Check out our GitHub repository and open a Pull Request." },
  { "question": "What is a Schema?", "answer": "A Schema defines the structure of the documents within a collection." },
  { "question": "Can I use multiple databases?", "answer": "Yes, NestJS allows you to connect to multiple MongoDB instances." },
  { "question": "What is the meaning of life?", "answer": "In binary, it's 101010. In reality, it's building cool apps." },
  { "question": "Is this a real person?", "answer": "No, I am an automated response system." },
  { "question": "What is JSON?", "answer": "JavaScript Object Notation is a lightweight format for storing and transporting data." },
  { "question": "Bye", "answer": "Goodbye! Have a great day!" }
]